name: Test Degree-Days

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate HACS and Hassfest
    steps:
        - uses: "actions/checkout@v4"

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
